### PR TITLE
Add interface to access relative residue areas. #3

### PR DESCRIPTION
**Pull request by mittinatten**

### CODE REVIEW

**Comment by mittinatten** [comment]
Only tested with Python3 so far

**Comment by ehfd** [comment]
With Py 3.7 and 1UBQ.pdb directly pulled from the PDB, this causes a Segmentation fault (core dumped):

```python
import freesasa
from Bio.PDB import PDBParser

parser = PDBParser()
structure = parser.get_structure("prot", "1UBQ.pdb")
result, sasa_classes = freesasa.calcBioPDB(structure)
residueAreas = result.residueAreas()
print(residueAreas)
```

This is specifically a problem with residueAreas after calcBioPDB.

**Comment by ehfd** [comment]
This is the raw data of 1UBQ comparing with DSSP and [PyMOL's implementation](https://github.com/schrodinger/pymol-open-source/blob/master/modules/pymol/util.py#L1063). 

The values are a bit biased to a larger value in edge cases especially vs comparisons. Try comparing with NACCESS too. Other than that, all set.
P.S. What MaxASA am I supposed to cite for the RSA value?

Code:
```python
import freesasa  # pip install freesasa or git clone
from Bio.PDB import PDBParser  # conda install -c conda-forge biopython
from Bio.PDB.DSSP import DSSP  # sudo apt-get install dssp
from pymol import cmd  # conda install -c schrodinger pymol

structure = freesasa.Structure("1UBQ.pdb")
result = freesasa.calc(structure)
residueAreas1 = result.residueAreas()
residueTotal1 = dict(map(lambda x: (x[0], x[1].relativeTotal), residueAreas1['A'].items()))
print(residueTotal1)

parser = PDBParser()
structure = parser.get_structure("prot", "1UBQ.pdb")
model = structure[0]
residueAreas2 = DSSP(model, "1UBQ.pdb")
residueTotal2 = dict(map(lambda x: (x[0][1][1], x[1][3]), dict(residueAreas2).items()))
print(residueTotal2)

cmd.load("1UBQ.pdb", "prot")
cmd.select("prt", "not het")
residueAreas3 = cmd.get_sasa_relative("prt")
residueTotal3 = dict(map(lambda x: (x[0][3], x[1]), residueAreas3.items()))
print(residueTotal3)
```

freesasa:
```{'1': 0.28168569591640524, '2': 0.41498689470497835, '3': 0.0, '4': 0.2740065079792209, '5': 1.2784285868491042e-06, '6': 0.48826158608631326, '7': 0.15046764248952238, '8': 0.7633529767428158, '9': 0.8898069138766252, '10': 0.832709371001403, '11': 0.5041117402798733, '12': 0.4462997377399443, '13': 0.027501978242297023, '14': 0.44167983462663357, '15': 0.03442414973249816, '16': 0.8025762038450126, '17': 0.03828995383454624, '18': 0.5763725332781171, '19': 0.36854719207120307, '20': 0.7003893093987684, '21': 0.22234661887885634, '22': 0.3496427035689502, '23': 0.0, '24': 0.6712741681599483, '25': 0.35407106616440526, '26': 0.0, '27': 0.08253312121910825, '28': 0.4381079839412358, '29': 0.33405875536250224, '30': 0.00048629574697986905, '31': 0.42143685070025694, '32': 0.9100734772155467, '33': 0.5517909226351045, '34': 0.3699100943319597, '35': 0.6118615161742307, '36': 0.16796407717767686, '37': 0.3829759728269163, '38': 0.3610654291107242, '39': 0.5888413525385631, '40': 0.2277530653351577, '41': 0.0001388670232241228, '42': 0.3706150659511096, '43': 0.0018176401640819181, '44': 0.1600637307002966, '45': 0.18803675016499222, '46': 0.6659824534983972, '47': 0.9239485725671036, '48': 0.48236165111048507, '49': 0.5689750703324532, '50': 0.03244781191550152, '51': 0.6603785166322498, '52': 0.42522027413824287, '53': 0.5816592088527729, '54': 0.518057790262954, '55': 0.23105900149135503, '56': 0.0, '57': 0.5386996018820289, '58': 0.6064501054695361, '59': 0.17211116726120992, '60': 0.7937572797174481, '61': 0.025542965373111633, '62': 0.6625654656888814, '63': 0.6578903749069719, '64': 0.5580642565918573, '65': 0.16570458282427192, '66': 0.3791304467916768, '67': 0.0, '68': 0.42904311521074345, '69': 0.014676127093707471, '70': 0.24442652290440042, '71': 0.43038626844901384, '72': 0.4936089065624725, '73': 0.6627738504027597, '74': 0.8855042757412734, '75': 0.9046160699873246, '76': 1.805594383299096}```

[DSSP & BioPython](https://biopython.org/DIST/docs/api/Bio.PDB.DSSP%27-module.html):
```{1: 0.28191489361702127, 2: 0.3888888888888889, 3: 0.0, 4: 0.27411167512690354, 5: 0.0, 6: 0.5024390243902439, 7: 0.14788732394366197, 8: 0.823170731707317, 9: 0.8732394366197183, 10: 0.7976190476190477, 11: 0.4682926829268293, 12: 0.4647887323943662, 13: 0.029585798816568046, 14: 0.43661971830985913, 15: 0.042682926829268296, 16: 0.7989690721649485, 17: 0.028169014084507043, 18: 0.5567010309278351, 19: 0.34558823529411764, 20: 0.6615384615384615, 21: 0.22699386503067484, 22: 0.33098591549295775, 23: 0.0, 24: 0.6701030927835051, 25: 0.3503184713375796, 26: 0.0, 27: 0.06341463414634146, 28: 0.41509433962264153, 29: 0.33170731707317075, 30: 0.0, 31: 0.42424242424242425, 32: 0.8957055214723927, 33: 0.526829268292683, 34: 0.3711340206185567, 35: 0.5952380952380952, 36: 0.17751479289940827, 37: 0.34558823529411764, 38: 0.3161764705882353, 39: 0.5153374233128835, 40: 0.25252525252525254, 41: 0.0, 42: 0.3790322580645161, 43: 0.0, 44: 0.15976331360946747, 45: 0.19289340101522842, 46: 0.660377358490566, 47: 0.8928571428571429, 48: 0.4878048780487805, 49: 0.5252525252525253, 50: 0.024390243902439025, 51: 0.6597938144329897, 52: 0.4049079754601227, 53: 0.5476190476190477, 54: 0.5040322580645161, 55: 0.20422535211267606, 56: 0.0, 57: 0.47692307692307695, 58: 0.5521472392638037, 59: 0.17567567567567569, 60: 0.7770700636942676, 61: 0.029585798816568046, 62: 0.6313131313131313, 63: 0.6390243902439025, 64: 0.5515463917525774, 65: 0.16153846153846155, 66: 0.39436619718309857, 67: 0.0, 68: 0.44565217391304346, 69: 0.03048780487804878, 70: 0.24647887323943662, 71: 0.4634146341463415, 72: 0.4637096774193548, 73: 0.7073170731707317, 74: 0.842741935483871, 75: 0.8928571428571429, 76: 1.0}```

[PyMOL](https://pymol.org/pymol-command-ref.html#get_sasa_relative):
```{'1': 0.236057744102188, '2': 0.44662207829200223, '3': 0.0, '4': 0.25736006606113226, '5': 0.0, '6': 0.5091720243258531, '7': 0.20983279593171877, '8': 0.7529062937660814, '9': 0.8567590884399557, '10': 0.7983149614697747, '11': 0.5085527096170954, '12': 0.5237541388102032, '13': 0.036872823636375986, '14': 0.4660056414928109, '15': 0.04708134356733452, '16': 0.7675346122152987, '17': 0.0420051894119569, '18': 0.6356736106810889, '19': 0.3331593964304834, '20': 0.7333116416956185, '21': 0.22782656620694763, '22': 0.35945142659182705, '23': 0.0040576470414903166, '24': 0.6402049594538021, '25': 0.35393399362598116, '26': 0.0052039360717525875, '27': 0.07143845423682772, '28': 0.4025527953890491, '29': 0.3262825114295636, '30': 0.008895380857044385, '31': 0.4321346889539311, '32': 0.853395388829236, '33': 0.6075214839689618, '34': 0.43614717347749815, '35': 0.566958103275174, '36': 0.18880922655800328, '37': 0.39269105676602495, '38': 0.33742609311906235, '39': 0.563662026192757, '40': 0.24763373621541368, '41': 0.0037787434181209513, '42': 0.3854115072905922, '43': 0.0, '44': 0.16830660379995263, '45': 0.1995870449161617, '46': 0.747208421972376, '47': 0.8244739458663366, '48': 0.473431988310006, '49': 0.5696118492995351, '50': 0.04351741174684708, '51': 0.6547159066387906, '52': 0.38765644302445823, '53': 0.7479933825262308, '54': 0.550254896041734, '55': 0.23242181600313114, '56': 0.0, '57': 0.5289111820355923, '58': 0.5993008621693272, '59': 0.19059255021363677, '60': 0.6932319917677043, '61': 0.035088810703336026, '62': 0.6708356487560281, '63': 0.7868181018531019, '64': 0.6101641916324517, '65': 0.1597847199773175, '66': 0.4083404007389412, '67': 0.004746114998798058, '68': 0.4605559060947031, '69': 0.053106725028858395, '70': 0.2652845584619014, '71': 0.47527595659208693, '72': 0.5323321749600743, '73': 0.657731834865261, '74': 0.86993265572437, '75': 0.8391732972002737, '76': 1.0}```

**Comment by mittinatten** [comment]
Right, this would not work for a structure initialized via BioPDB, only if it is opened using `freesasa.Structure("/path/to/pdb")` as you did in your second example. Fixing that is a big task, not sure when/if that's possible. But there should be a better error message, so I'll look into that.

The maxASA are calculcated using the classifier used, so we have one separate set for the ProtOr, OONS and NACCESS classifiers. The max values were calculated using the same reference pdb-files that were originally used in NACCESS back in the day. Sometimes the relative value can be larger than 1 (because the reference conformations are approximations of the most exposed conformation). The reference values can be extracted from the source here: https://github.com/mittinatten/freesasa/blob/master/src/classifier_protor.c#L39, and corresponding lines for other residues, but it's not very easy to read (you'll have to compare with the struct declaration to get the order of properties: https://github.com/mittinatten/freesasa/blob/master/src/freesasa.h#L268).

If you do roughly this:
```
classifier = freesasa.Classifier.getStandardClassifier("naccess")
structure = freesasa.Structure("1ubq.pdb", classifier)
# ... the rest is the same as in your example
```
You should get the same result as with naccess (except that naccess reports the relative values as percentages), given that you use the same number of slices.

**Comment by ehfd** [comment]
Very well. Inability to use Bio.PDB is a minimal issue but it's just using one more module separate from the Biopython pipeline, so I could deal with it. Let's merge it as long as the behavior is same as CLI.

**Comment by mittinatten** [comment]
I thought more about the BioPDB case, and realized there shouldn't be a reason it fails. There were some subtleties with object scope and deallocation that caused the conflict. 

~~I found a hack that solves it for now, and also provided a short cut. At some later point me/someone should probably see if there is a better solution than my hack, but it might require some refactoring. So I will merge this as soon as the tests pass.~~

**Comment by mittinatten** [comment]
It's merged!

I'll let this be for a week or so before I publish the package. Just to see if there's more documentation fixes, tests or other tweaks that should be there.

**Comment by mittinatten** [comment]
Published it as a beta in the mean time https://pypi.org/project/freesasa/2.1.0b1/

**Comment by mittinatten** [comment]
https://pypi.org/project/freesasa/2.1.0/

**Pull request merged**
