### PR TITLE
add new function addAtoms

### PR DESCRIPTION
**Pull request by ghost**
Add a supplement function `addAtoms` so that users don't need to repeatedly do `addAtom` on their side.

### CODE REVIEW

**Comment by mittinatten** [comment]
Hi!
This looks nice and makes sense. Seems there are some problems with the Travis build that are probably unrelated, I will fix that and come back to you.

In the mean time, could you add one or two simple tests to `test.py` for this feature?

**Comment by ghost** [comment]
I added some tests and they look fine :smile:

**Comment by mittinatten** [comment]
Sorry for the  slow responses here. I have updated the Travis config, so that the master branch builds again. Could you merge the master branch into this PR so we can verify that everything's ok here too?

**Comment by mittinatten** [comment]
On second thought, I think I will just merge it myself, pretty sure everything is ok here. Thanks for the contribution!

**Pull request merged**
